# Generated by Django 3.2.19 on 2023-07-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_bookmark_like_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
